name: Build docker image and push

on:
  push:
    paths:
      - 'server-release-versions'
      
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Get available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Get version name
        id: version
        run: echo "::set-output name=version::$(cat ./server-release-versions)"
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          file: ./Dockerfile
          platforms: linux/arm64,linux/amd64
          tags: |
            ricky9w/mindustry-server:${{ steps.version.outputs.version }}
            ricky9w/mindustry-server:latest
